### ISSUE TITLE
docker_pyhss is exiting due to permission issues in SQL

### ISSUE THREAD

**Issue by panyogesh** [herlesupreeth/docker_open5gs#204]
Sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1044, "Access denied for user 'pyhss'@'172.22.0.18' to database 'ims_hss_db'")

**Comment by herlesupreeth** [comment]
Can you please post the entire log??

**Comment by panyogesh** [comment]
agrant@vonr-2004-ubuntu:~/docker_open5gs$ sudo docker logs -f c0f2a73559fb
mysqld is alive
/pyhss/database.py:1109: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if page_size is not 0:
Instantiating LogTool with Kwargs dict_items([])
Instantiating LogTool with Kwargs dict_items([])
Instantiating LogTool with Kwargs dict_items([])
mysql://pyhss:ims_db_pass@172.22.0.17/ims_hss_db?autocommit=true
Instantiating LogTool with Kwargs dict_items([])
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1044, "Access denied for user 'pyhss'@'172.22.0.18' to database 'ims_hss_db'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hss.py", line 16, in <module>
    import diameter as DiameterLib
  File "/pyhss/diameter.py", line 29, in <module>
    import database
  File "/pyhss/database.py", line 300, in <module>
    create_database(engine.url)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy_utils/functions/database.py", line 582, in create_database
    conn.execute(sa.text(text))
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1044, "Access denied for user 'pyhss'@'172.22.0.18' to database 'ims_hss_db'")
[SQL: CREATE DATABASE ims_hss_db CHARACTER SET = 'utf8']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
mysqld is alive
Instantiating LogTool with Kwargs dict_items([])
Instantiating LogTool with Kwargs dict_items([])
Instantiating LogTool with Kwargs dict_items([])
mysql://pyhss:ims_db_pass@172.22.0.17/ims_hss_db?autocommit=true
Instantiating LogTool with Kwargs dict_items([])
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1044, "Access denied for user 'pyhss'@'172.22.0.18' to database 'ims_hss_db'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hss.py", line 16, in <module>
    import diameter as DiameterLib
  File "/pyhss/diameter.py", line 29, in <module>
    import database
  File "/pyhss/database.py", line 300, in <module>
    create_database(engine.url)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy_utils/functions/database.py", line 582, in create_database
    conn.execute(sa.text(text))
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1044, "Access denied for user 'pyhss'@'172.22.0.18' to database 'ims_hss_db'")
[SQL: CREATE DATABASE ims_hss_db CHARACTER SET = 'utf8']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
mysql://pyhss:ims_db_pass@172.22.0.17/ims_hss_db?autocommit=true
Instantiating LogTool with Kwargs dict_items([])
Instantiating LogTool with Kwargs dict_items([])
Instantiating LogTool with Kwargs dict_items([])
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 1050, in main
    cli.main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/pyhss/PyHSS_API.py", line 27, in <module>
    import database
  File "/pyhss/database.py", line 300, in <module>
    create_database(engine.url)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy_utils/functions/database.py", line 582, in create_database
    conn.execute(sa.text(text))
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1044, "Access denied for user 'pyhss'@'172.22.0.18' to database 'ims_hss_db'")
[SQL: CREATE DATABASE ims_hss_db CHARACTER SET = 'utf8']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
mysqld is alive
Instantiating LogTool with Kwargs dict_items([])
Instantiating LogTool with Kwargs dict_items([])
Instantiating LogTool with Kwargs dict_items([])
mysql://pyhss:ims_db_pass@172.22.0.17/ims_hss_db?autocommit=true
Instantiating LogTool with Kwargs dict_items([])
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1044, "Access denied for user 'pyhss'@'172.22.0.18' to database 'ims_hss_db'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hss.py", line 16, in <module>
    import diameter as DiameterLib
  File "/pyhss/diameter.py", line 29, in <module>
    import database
  File "/pyhss/database.py", line 300, in <module>
    create_database(engine.url)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy_utils/functions/database.py", line 582, in create_database
    conn.execute(sa.text(text))
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1044, "Access denied for user 'pyhss'@'172.22.0.18' to database 'ims_hss_db'")
[SQL: CREATE DATABASE ims_hss_db CHARACTER SET = 'utf8']
(Background on this error at: https://sqlalche.me/e/20/e3q8)
vagrant@vonr-2004-ubuntu:~/docker_open5gs$

**Comment by panyogesh** [comment]
Steps to reproduce : 
  - docker-compose -f 4g-volte-deploy.yaml up (pyhss is logging out after sometime).
   -  No other operation

**Comment by herlesupreeth** [comment]
Can you try bringing down all the components (docker-compose -f 4g-volte-deploy.yaml down). Wait for it. And then bring it back up again?? And see if the issue persists??

**Comment by herlesupreeth** [comment]
You need to reupload the logs. You pressed comment before logs got uploaded

**Comment by panyogesh** [comment]
[Issue-Logs-Related-to-PyHSS.txt](https://github.com/herlesupreeth/docker_open5gs/files/12299868/Issue-Logs-Related-to-PyHSS.txt)

**Comment by herlesupreeth** [comment]
I just re-deployed pyhss on a fresh setup and I dont see this issue at all. I would suggest the following.

1. Pull the latest changes from master branch
2. Drop the mysql docker volume (`docker volume rm docker_open5gs_dbdata`)
3. Rebuild pyHSS docker image (`docker-compose -f 4g-volte-deploy.yaml --no-cache pyhss`)
4. Re-deploy all containers
