### ISSUE TITLE
Error while docker compose UP

### ISSUE THREAD

**Issue by modyngs** [herlesupreeth/docker_open5gs#21]
Dear @herlesupreeth 
Hi
I followed this instruction, but when i did docker compose up face with this issue:

```
~/docker_open5gs$ docker-compose up
Creating network "docker_open5gs_default" with the default driver
Creating volume "docker_open5gs_mongodbdata" with default driver
Creating volume "docker_open5gs_dbdata" with default driver
Creating nrf       ... done
Creating dns       ... done
Creating mongo ... 
Creating mysql ... 
Creating rtpengine ... done
Creating mongo     ... done
Creating smf       ... 
Creating udm       ... 

ERROR: for smf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
Creating hss       ... 
Creating mysql     ... done
Creating webui     ... 
Creating ausf      ... done

Creating udm       ... done
mote_port]:]port[/protocol]

Creating webui     ... done
Creating pcf       ... done
Creating udr       ... done
Creating fhoss     ... done
Creating icscf     ... done
Creating scscf     ... done
Creating pcscf     ... done

ERROR: for smf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for hss  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for pcrf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1052, in up
  File "compose/cli/main.py", line 1048, in up
  File "compose/project.py", line 496, in up
  File "compose/parallel.py", line 105, in parallel_execute
  File "compose/parallel.py", line 203, in producer
  File "compose/project.py", line 482, in do
  File "compose/service.py", line 505, in execute_convergence_plan
  File "compose/service.py", line 427, in _execute_convergence_create
  File "compose/parallel.py", line 105, in parallel_execute
  File "compose/parallel.py", line 203, in producer
  File "compose/service.py", line 425, in <lambda>
  File "compose/service.py", line 416, in create_and_start
  File "compose/service.py", line 315, in create_container
  File "compose/service.py", line 820, in _get_container_create_options
  File "compose/service.py", line 1600, in build_container_ports
  File "site-packages/docker/utils/ports.py", line 65, in split_port
  File "site-packages/docker/utils/ports.py", line 43, in _raise_invalid_port
ValueError: Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
[13812] Failed to execute script docker-compose
```

I did not run anythiing under root!

**Comment by herlesupreeth** [comment]
Check your docker version and docker-compose version. It should atleast as referred in this comment - https://github.com/herlesupreeth/docker_open5gs/issues/6#issuecomment-701342639

**Comment by modyngs** [comment]
Thanks
