### ISSUE TITLE
pcscf error

### ISSUE THREAD

**Issue by zhouxiang93123** [herlesupreeth/docker_open5gs#63]
hi , when I tested this docker, pcscf has errors.
mme        | 12/06 21:01:06.359: [mme] INFO: eNB-S1 accepted[192.168.1.151]:59256 in s1_path module (../src/mme/s1ap-sctp.c:106)
mme        | 12/06 21:01:06.359: [mme] INFO: eNB-S1 accepted[192.168.1.151] in master_sm module (../src/mme/mme-sm.c:152)
mme        | 12/06 21:01:06.360: [mme] INFO: [ENB] max_num_of_ostreams : 30 (../src/mme/mme-context.c:1789)
mme        | 12/06 21:01:06.360: [mme] INFO: [Added] Number of eNBs is now 1 (../src/mme/mme-context.c:1804)
webui      | Mongoose: accounts.findOne({ '$or': [ { username: 'admin' } ] }, { fields: { hash: 0, salt: 0 } })
mme        | 12/06 21:01:09.004: [mme] INFO: InitialUEMessage (../src/mme/s1ap-handler.c:223)
mme        | 12/06 21:01:09.004: [mme] INFO: [Added] Number of eNB-UEs is now 1 (../src/mme/mme-context.c:3240)
mme        | 12/06 21:01:09.004: [mme] INFO:     ENB_UE_S1AP_ID[1] MME_UE_S1AP_ID[1] TAC[1] CellID[0x1a2d021] (../src/mme/s1ap-handler.c:363)
mme        | 12/06 21:01:09.004: [mme] INFO: [460110123456793] Unknown UE by IMSI (../src/mme/mme-context.c:2306)
mme        | 12/06 21:01:09.004: [mme] INFO: [Added] Number of MME-UEs is now 1 (../src/mme/mme-context.c:2148)
mme        | 12/06 21:01:09.004: [emm] WARNING: [] Attach request (../src/mme/emm-sm.c:203)
mme        | 12/06 21:01:09.004: [emm] INFO:     IMSI[460110123456793] (../src/mme/emm-handler.c:174)
mme        | 12/06 21:01:09.969: [mme] INFO: [Added] Number of MME-Sessions is now 1 (../src/mme/mme-context.c:3252)
sgwc       | 12/06 21:01:09.970: [sgwc] INFO: [Added] Number of SGWC-UEs is now 1 (../src/sgwc/context.c:210)
sgwc       | 12/06 21:01:09.970: [sgwc] INFO: [Added] Number of SGWC-Sessions is now 1 (../src/sgwc/context.c:863)
sgwu       | 12/06 21:01:09.970: [sgwu] INFO: UE F-SEID[CP:0x1 UP:0x1] (../src/sgwu/context.c:144)
sgwu       | 12/06 21:01:09.970: [sgwu] INFO: [Added] Number of SGWU-Sessions is now 1 (../src/sgwu/context.c:149)
sgwc       | 12/06 21:01:09.971: [gtp] INFO: gtp_connect() [172.22.0.7]:2123 (../lib/gtp/path.c:58)
smf        | 12/06 21:01:09.971: [smf] INFO: [Added] Number of SMF-UEs is now 1 (../src/smf/context.c:819)
smf        | 12/06 21:01:09.971: [smf] INFO: [Added] Number of SMF-Sessions is now 1 (../src/smf/context.c:2610)
smf        | 12/06 21:01:09.971: [smf] INFO: UE IMSI[460110123456793] APN[ctnet] IPv4[192.168.100.2] IPv6[] (../src/smf/s5c-handler.c:223)
upf        | 12/06 21:01:09.977: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:160)
upf        | 12/06 21:01:09.978: [gtp] INFO: gtp_connect() [192.168.1.173]:2152 (../lib/gtp/path.c:58)
upf        | 12/06 21:01:09.978: [gtp] INFO: gtp_connect() [172.22.0.7]:2152 (../lib/gtp/path.c:58)
upf        | 12/06 21:01:09.978: [upf] INFO: UE F-SEID[CP:0x1 UP:0x1] APN[ctnet] PDN-Type[1] IPv4[192.168.100.2] IPv6[] (../src/upf/context.c:361)
smf        | 12/06 21:01:09.978: [gtp] INFO: gtp_connect() [172.22.0.8]:2152 (../lib/gtp/path.c:58)
smf        | 12/06 21:01:09.978: [smf] WARNING: Unknown PCO ID:(0x2) (../src/smf/context.c:2537)
sgwu       | 12/06 21:01:09.979: [gtp] INFO: gtp_connect() [172.22.0.8]:2152 (../lib/gtp/path.c:58)
mme        | 12/06 21:01:10.084: [emm] INFO: [460110123456793] Attach complete (../src/mme/emm-sm.c:1018)
mme        | 12/06 21:01:10.084: [emm] INFO:     IMSI[460110123456793] (../src/mme/emm-handler.c:223)
mme        | 12/06 21:01:10.084: [emm] INFO:     UTC [2021-12-06T13:01:10] Timezone[0]/DST[0] (../src/mme/emm-handler.c:229)
mme        | 12/06 21:01:10.084: [emm] INFO:     LOCAL [2021-12-06T21:01:10] Timezone[28800]/DST[0] (../src/mme/emm-handler.c:233)
sgwu       | 12/06 21:01:10.085: [gtp] INFO: gtp_connect() [192.168.1.151]:2152 (../lib/gtp/path.c:58)
mme        | 12/06 21:01:10.144: [mme] INFO: [Added] Number of MME-Sessions is now 2 (../src/mme/mme-context.c:3252)
sgwc       | 12/06 21:01:10.144: [sgwc] INFO: [Added] Number of SGWC-Sessions is now 2 (../src/sgwc/context.c:863)
sgwu       | 12/06 21:01:10.145: [sgwu] INFO: UE F-SEID[CP:0x2 UP:0x2] (../src/sgwu/context.c:144)
sgwu       | 12/06 21:01:10.145: [sgwu] INFO: [Added] Number of SGWU-Sessions is now 2 (../src/sgwu/context.c:149)
smf        | 12/06 21:01:10.145: [smf] INFO: [Added] Number of SMF-Sessions is now 2 (../src/smf/context.c:2610)
smf        | 12/06 21:01:10.145: [smf] INFO: UE IMSI[460110123456793] APN[ims] IPv4[192.168.101.2] IPv6[] (../src/smf/s5c-handler.c:223)
upf        | 12/06 21:01:10.151: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:160)
upf        | 12/06 21:01:10.151: [upf] INFO: UE F-SEID[CP:0x2 UP:0x2] APN[ims] PDN-Type[1] IPv4[192.168.101.2] IPv6[] (../src/upf/context.c:361)
smf        | 12/06 21:01:10.151: [smf] WARNING: Unknown PCO ID:(0x2) (../src/smf/context.c:2537)
pcscf      | 101(137) NOTICE: <script>: PCSCF: REGISTER sip:ims.mnc011.mcc460.3gppnetwork.org (sip:460110123456793@ims.mnc011.mcc460.3gppnetwork.org (192.168.101.2:5060) to sip:460110123456793@ims.mnc011.mcc460.3gppnetwork.org, qqhcbgZt8@192.168.101.2)
pcscf      | 101(137) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
pcscf      | 101(137) NOTICE: <script>: PCSCF REGISTER: 
pcscf      |  Destination URI: <null>
pcscf      |  Request URI: sip:ims.mnc011.mcc460.3gppnetwork.org
pcscf      | 101(137) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
pcscf      | 101(137) NOTICE: <script>: Source IP and Port: (192.168.101.2:5060)
pcscf      |  Route-URI: 
pcscf      | 101(137) NOTICE: <script>: Received IP and Port: (172.22.0.21:5060)
pcscf      | 101(137) NOTICE: <script>: Contact header: <sip:460110123456793@192.168.101.2:5060>;+sip.instance="<urn:gsma:imei:86637105-402285-0>";+g.3gpp.accesstype="cellular2";audio;video;+g.3gpp.smsip;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel"
pcscf      | 101(137) INFO: ims_registrar_pcscf [sec_agree.c:296]: cscf_get_security_verify(): No security-verify parameters found
pcscf      | 101(137) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after callback of event 1
pcrf       | 12/06 21:01:10.350: [pcrf] WARNING: Not supported(260) (../src/pcrf/pcrf-rx-path.c:430)
pcrf       | 12/06 21:01:10.350: [pcrf] WARNING: Not supported(524) (../src/pcrf/pcrf-rx-path.c:420)
pcrf       | 12/06 21:01:10.351: [pcrf] WARNING: Not supported(524) (../src/pcrf/pcrf-rx-path.c:420)
pcrf       | 12/06 21:01:10.351: [pcrf] WARNING: Not supported(291) (../src/pcrf/pcrf-rx-path.c:430)
pcrf       | 12/06 21:01:10.351: [pcrf] WARNING: Not supported(276) (../src/pcrf/pcrf-rx-path.c:430)
pcrf       | 12/06 21:01:10.351: [pcrf] WARNING: Not supported(27) (../src/pcrf/pcrf-rx-path.c:430)
pcscf      | 94(130) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after callback of event 7
pcscf      | 90(126) INFO: <core> [core/tcp_main.c:3010]: tcpconn_1st_send(): quick connect for 0x7f76a56ef438
icscf      | 31(60) INFO: ims_icscf [cxdx_uar.c:71]: create_uaa_return_code(): created AVP successfully : [uaa_return_code]
fhoss      | de.fhg.fokus.hss.cx.CxFinalResultException: Diameter_Authorization_Rejected
fhoss      | 	at de.fhg.fokus.hss.cx.op.UAR.processRequest(UAR.java:134)
fhoss      | 	at de.fhg.fokus.hss.main.Task.execute(Task.java:169)
fhoss      | 	at de.fhg.fokus.hss.main.Worker.run(Worker.java:66)
icscf      |  9(38) INFO: ims_icscf [cxdx_avp.c:137]: cxdx_get_avp(): cxdx_get_server_name: Failed finding avp
icscf      |  9(38) INFO: ims_icscf [cxdx_avp.c:137]: cxdx_get_avp(): cxdx_get_capabilities: Failed finding avp
icscf      |  9(38) INFO: ims_icscf [cxdx_avp.c:137]: cxdx_get_avp(): cxdx_get_experimental_result_code: Failed finding avp
icscf      |  9(38) INFO: ims_icscf [cxdx_uar.c:71]: create_uaa_return_code(): created AVP successfully : [uaa_return_code]
icscf      |  9(38) WARNING: tm [t_suspend.c:192]: t_continue_helper(): active transaction not found
pcscf      | 101(137) ERROR: <core> [core/tcp_read.c:299]: tcp_read_data(): error reading: Connection reset by peer (104) ([192.168.101.2]:5060 ->101(137) ERROR: <core> [core/tcp_read.c:303]: tcp_read_data(): -> [172.22.0.21]:5060)
pcscf      | 101(137) ERROR: <core> [core/tcp_read.c:1503]: tcp_read_req(): ERROR: tcp_read_req: error reading - c: 0x7f76a56e3ec0 r: 0x7f76a56e3f40 (-1)
pcscf      | 94(130) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after callback of event 5
pcscf      | 94(130) INFO: cdp [authstatemachine.c:741]: Send_ASA(): Send_ASA():  sending ASA
pcscf      | 94(130) INFO: cdp [authstatemachine.c:766]: Send_ASA(): sending ASA to peer pcrf.epc.mnc011.mcc460.3gppnetwork.org
pcscf      | 94(130) INFO: cdp [authstatemachine.c:773]: Send_ASA(): success sending ASA
pcscf      | 94(130) ERROR: cdp [routing.c:274]: get_routing_peer(): get_routing_peer(): No connected DefaultRoute peer found for app_id 16777236 and vendor id 0.
pcscf      | 94(130) ERROR: cdp [authstatemachine.c:870]: Send_STR(): unable to get routing peer in Send_STR 
pcscf      | 89(125) INFO: ims_qos [ims_qos_mod.c:399]: callback_cdp_request(): Rx request handler(): - Received an IMS_ASR 
upf        | 12/06 21:01:10.458: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:190)
smf        | 12/06 21:01:10.458: [smf] WARNING: Unknown PCO ID:(0x2) (../src/smf/context.c:2537)
smf        | 12/06 21:01:10.458: [smf] INFO: Removed Session: UE IMSI:[460110123456793] DNN:[ims:0] IPv4:[192.168.101.2] IPv6:[] (../src/smf/context.c:1407)
smf        | 12/06 21:01:10.458: [smf] INFO: [Removed] Number of SMF-Sessions is now 1 (../src/smf/context.c:2616)
sgwu       | 12/06 21:01:10.459: [sgwu] INFO: [Removed] Number of SGWU-sessions is now 1 (../src/sgwu/context.c:169)
sgwc       | 12/06 21:01:10.459: [sgwc] INFO: [Removed] Number of SGWC-Sessions is now 1 (../src/sgwc/context.c:869)
mme        | 12/06 21:01:10.484: [mme] INFO: [Removed] Number of MME-Sessions is now 1 (../src/mme/mme-context.c:3258)
webui      | Mongoose: accounts.findOne({ '$or': [ { username: 'admin' } ] }, { fields: { hash: 0, salt: 0 } })

**Comment by zhouxiang93123** [comment]
Here is pcap file.
Thanks!

[test_pcap.zip](https://github.com/herlesupreeth/docker_open5gs/files/7666787/test_pcap.zip)

**Comment by herlesupreeth** [comment]
There is no issue with PCSCF, rather you have issue in provisioning of UE SIM details in HSS (IMS - FHOSS) and authorization is rejected

![image](https://user-images.githubusercontent.com/4115839/145033156-adcdd762-2971-4fae-b830-37f969ed406f.png)

**Comment by zhouxiang93123** [comment]
> There is no issue with PCSCF, rather you have issue in provisioning of UE SIM details in HSS (IMS - FHOSS) and authorization is rejected
> 
> ![image](https://user-images.githubusercontent.com/4115839/145033156-adcdd762-2971-4fae-b830-37f969ed406f.png)

Thank you for your response!!
Dose It mean that  the errors of pcscf  can  be ignored ?
I will check the details in HSS and I'll let you know what will happens.
Can I follow the steps   **20. Add IMS subscription use in FoHSS as follows from the Web GUI**  shown in https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/  to  complete the authorization?

**Comment by herlesupreeth** [comment]
Yes, you can ignore pcscf errors. And yes you can use step 20 in that guide to provision user in fhoss
