### ISSUE TITLE
Build Failed docker-compose up 

### ISSUE THREAD

**Issue by Johann-Orozco** [herlesupreeth/docker_open5gs#95]
good afternoon everyone 

I have a problem when I run the command docker-compose up, I receive this response, could you help me please to find the problem 

----------------------------------

open5gc@open5gc:~/docker_open5gs$ sudo docker-compose -f srsgnb.yaml up -d && docker attach srsgnb
WARNING: Found orphan containers (pcscf, scscf, icscf, fhoss, smsc, udm, bsf, pcf, ausf, udr, nssf, webui, rtpengine, nrf, dns, osmohlr, mysql, mongo) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating srsgnb ... 

ERROR: for srsgnb  Invalid port "38412/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for srsgnb  Invalid port "38412/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1052, in up
  File "compose/cli/main.py", line 1048, in up
  File "compose/project.py", line 496, in up
  File "compose/parallel.py", line 105, in parallel_execute
  File "compose/parallel.py", line 203, in producer
  File "compose/project.py", line 482, in do
  File "compose/service.py", line 505, in execute_convergence_plan
  File "compose/service.py", line 427, in _execute_convergence_create
  File "compose/parallel.py", line 105, in parallel_execute
  File "compose/parallel.py", line 203, in producer
  File "compose/service.py", line 425, in <lambda>
  File "compose/service.py", line 416, in create_and_start
  File "compose/service.py", line 315, in create_container
  File "compose/service.py", line 820, in _get_container_create_options
  File "compose/service.py", line 1600, in build_container_ports
  File "site-packages/docker/utils/ports.py", line 65, in split_port
  File "site-packages/docker/utils/ports.py", line 43, in _raise_invalid_port
ValueError: Invalid port "38412/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
[17052] Failed to execute script docker-compose
open5gc@open5gc:~/docker_open5gs$ 
open5gc@open5gc:~/docker_open5gs$ 
open5gc@open5gc:~/docker_open5gs$ 
open5gc@open5gc:~/docker_open5gs$ 
open5gc@open5gc:~/docker_open5gs$ 
open5gc@open5gc:~/docker_open5gs$ 
open5gc@open5gc:~/docker_open5gs$ sudo docker-compose up
mysql is up-to-date
osmohlr is up-to-date
dns is up-to-date
nrf is up-to-date
rtpengine is up-to-date
mongo is up-to-date
Creating osmomsc ... 
smsc is up-to-date
fhoss is up-to-date
ausf is up-to-date

ERROR: for osmomsc  Invalid port "29118/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
Creating smf     ... 
udm is up-to-date
webui is up-to-date

ERROR: for smf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
nssf is up-to-date
Creating pcrf    ... 
pcf is up-to-date
bsf is up-to-date

ERROR: for pcrf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
Creating hss     ... 
udr is up-to-date
icscf is up-to-date
scscf is up-to-date

ERROR: for hss  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
pcscf is up-to-date

ERROR: for osmomsc  Invalid port "29118/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for smf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for pcrf  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

ERROR: for hss  Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1052, in up
  File "compose/cli/main.py", line 1048, in up
  File "compose/project.py", line 496, in up
  File "compose/parallel.py", line 105, in parallel_execute
  File "compose/parallel.py", line 203, in producer
  File "compose/project.py", line 482, in do
  File "compose/service.py", line 505, in execute_convergence_plan
  File "compose/service.py", line 427, in _execute_convergence_create
  File "compose/parallel.py", line 105, in parallel_execute
  File "compose/parallel.py", line 203, in producer
  File "compose/service.py", line 425, in <lambda>
  File "compose/service.py", line 416, in create_and_start
  File "compose/service.py", line 315, in create_container
  File "compose/service.py", line 820, in _get_container_create_options
  File "compose/service.py", line 1600, in build_container_ports
  File "site-packages/docker/utils/ports.py", line 65, in split_port
  File "site-packages/docker/utils/ports.py", line 43, in _raise_invalid_port
ValueError: Invalid port "3868/sctp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
[17227] Failed to execute script docker-compose
open5gc@open5gc:~/docker_open5gs$ 

------------------
response to command " Docker ps" 

open5gc@open5gc:~/docker_open5gs$ sudo docker ps 
CONTAINER ID   IMAGE              COMMAND                  CREATED       STATUS       PORTS                                                                                                NAMES
870c07dbbf29   docker_kamailio    "/bin/sh -c /kamaili…"   2 hours ago   Up 2 hours   3871/tcp, 3871/udp, 5060/tcp, 5060/udp, 5100-5120/tcp, 5100-5120/udp, 6100-6120/tcp, 6100-6120/udp   pcscf
9377b01a9d41   docker_kamailio    "/bin/sh -c /kamaili…"   2 hours ago   Up 2 hours   3870/tcp, 3870/udp, 6060/tcp, 6060/udp                                                               scscf
b066ada96f1e   docker_kamailio    "/bin/sh -c /kamaili…"   2 hours ago   Up 2 hours   3869/tcp, 3869/udp, 4060/tcp, 4060/udp                                                               icscf
f094623f27aa   docker_fhoss       "/bin/sh -c /mnt/fho…"   2 hours ago   Up 2 hours   3868/tcp, 3868/udp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                        fhoss
90078fd096bd   docker_kamailio    "/bin/sh -c /kamaili…"   2 hours ago   Up 2 hours   7090/tcp, 7090/udp                                                                                   smsc
c9b0b25873cd   docker_open5gs     "/bin/sh -c /open5gs…"   2 hours ago   Up 2 hours   7777/tcp                                                                                             udm
630683a90a79   docker_open5gs     "/bin/sh -c /open5gs…"   2 hours ago   Up 2 hours   7777/tcp                                                                                             bsf
112b8b376b27   docker_open5gs     "/bin/sh -c /open5gs…"   2 hours ago   Up 2 hours   7777/tcp                                                                                             pcf
a40b484ac1be   docker_open5gs     "/bin/sh -c /open5gs…"   2 hours ago   Up 2 hours   7777/tcp                                                                                             ausf
8ddd9709fdd7   docker_open5gs     "/bin/sh -c /open5gs…"   2 hours ago   Up 2 hours   7777/tcp                                                                                             udr
21f92a0596f7   docker_open5gs     "/bin/sh -c /open5gs…"   2 hours ago   Up 2 hours   7777/tcp                                                                                             nssf
450767c56784   docker_open5gs     "/bin/sh -c /open5gs…"   2 hours ago   Up 2 hours   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                            webui
5494c7b8abb7   docker_rtpengine   "/bin/sh -c /mnt/rtp…"   2 hours ago   Up 2 hours   2223/udp, 49000-50000/udp                                                                            rtpengine
0eaf61378b72   docker_open5gs     "/bin/sh -c /open5gs…"   2 hours ago   Up 2 hours   7777/tcp                                                                                             nrf
0cab6b275e18   docker_dns         "/bin/sh -c '/mnt/dn…"   2 hours ago   Up 2 hours   53/udp                                                                                               dns
7484c62cabe8   docker_osmohlr     "/bin/sh -c '/mnt/os…"   2 hours ago   Up 2 hours   4222/tcp                                                                                             osmohlr
de0c9876fc04   docker_mysql       "/bin/sh -c /mysql_i…"   2 hours ago   Up 2 hours   3306/tcp                                                                                             mysql
ecd1ec26eeeb   docker_mongo       "/bin/sh -c /mnt/mon…"   2 hours ago   Up 2 hours   27017/tcp, 27017/udp                                                                                 mongo
open5gc@open5gc:~/docker_open5gs$

**Comment by herlesupreeth** [comment]
Try updating docker and docker-compose to following versions and give it a try

```
Docker version 20.10.17, build 100c701
Docker Compose version v2.1.1
```

**Comment by herlesupreeth** [comment]
Closing due to inactivity. Please re-open the issue with pcaps and logs if you still face issue.
